steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/momentlab-repo/backend:$COMMIT_SHA', './backend']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/momentlab-repo/backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'momentlab-backend'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/momentlab-repo/backend:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--project'
      - '$PROJECT_ID'

substitutions:
  _REGION: us-central1
